version: '3'
services:
  app:
    container_name: ci-cd-exemple_app
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./dev.db:/usr/src/app/dev.db
    ports:
      - '3000:3000'
